# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LeYT8hXYCNsehp8YV0Kn5W2zZvPLJo6r
"""

print('Bem-vindo a Loja do Ruan Dias de Souza RU:4651059')
valor = float(input('Entre com o valor unitario do produto: '))
quantidade = int(input('Entre com a quantidade do produto: '))

#Variavel para validação da lógica
valor_multiplicado = valor * quantidade
if valor_multiplicado < 2500:
            print('O valor sem o descontro foi R${} '.format(valor_multiplicado))
elif valor_multiplicado >= 2500.00 and valor_multiplicado <= 5999:
            porcento = (4/100)
            resultado_porcento = valor_multiplicado - porcento
            print('O valor sem o descontro foi R${} '.format(valor_multiplicado))
            print('O valor com desconto foi R${} (desconto {}%)'.format(resultado_porcento, porcento ))
elif valor_multiplicado >= 6000 and valor_multiplicado <= 9999:
            porcento = (7/100)
            resultado_porcento = valor_multiplicado - porcento
            print('O valor sem o descontro foi R${} '.format(valor_multiplicado))
            print('O valor com desconto foi R${} (desconto {}%)'.format(resultado_porcento, porcento ))
elif valor_multiplicado >= 10000:
            porcento = (11/100)
            resultado_porcento = valor_multiplicado - porcento
            print('O valor sem o descontro foi R${} '.format(valor_multiplicado))
            print('O valor com desconto foi R${} (desconto {}%)'.format(resultado_porcento, porcento))

# Funções
def escolha_sabor(sabor):
    while True:
        if sabor.lower() == 'cp' or sabor.lower() == 'ac':
            return sabor
        else:
            print('Escolha um sabor válido')
            sabor = input('Escolha o sabor (CP/AC): ').lower()

def escolha_tamanho(tamanho):
    while True:
        if tamanho.lower() == 'p' or tamanho.lower() == 'm' or tamanho.lower() == 'g':
            return tamanho
        else:
            print('Escolha um tamanho válido')
            tamanho = input('Escolha o tamanho (P/M/G): ').lower()

def pedido_inicial(sabor, tamanho):
    if sabor.lower() == 'cp':
        if tamanho.lower() == 'p':
            return 10.00
        elif tamanho.lower() == 'm':
            return 15.00
        elif tamanho.lower() == 'g':
            return 19.00
    elif sabor.lower() == 'ac':
        if tamanho.lower() == 'p':
            return 12.00
        elif tamanho.lower() == 'm':
            return 17.00
        elif tamanho.lower() == 'g':
            return 21.00

def adicionando_pedido(sabor, tamanho, pedidos):
    total_pedido = pedido_inicial(sabor, tamanho)
    #Metodo .append referência https://www.w3schools.com/python/ref_list_append.asp
    pedidos.append(total_pedido)
    while True:
        adicionar = input('Deseja pedir mais alguma coisa? (S/N): ').lower()
        if adicionar == 's':
            novo_sabor = input('Escolha o sabor (CP/AC): ').lower()
            novo_tamanho = input('Escolha o tamanho (P/M/G): ').lower()
            total_pedido = pedido_inicial(novo_sabor, novo_tamanho)
            pedidos.append(total_pedido)
        elif adicionar == 'n':
            break
        else:
            print('Escolha uma opção válida')

# Programa principal
#Lista para armazenar os valores dos pedidos
pedidos = []

print('Bem-vindo a Loja de Gelados do Ruan Dias de Souza')
print('-' * 35, 'Cardápio', '-' * 35)
print('-----' * 4, '|    Tamanho |', ' CUPUAÇU (CP)', '| AÇAÍ (AC) |', '-----' * 4)
print('-----' * 4, '|      P', '    |  R$ 10,00     |', ' R$ 12,00 |', '-----' * 4)
print('-----' * 4, '|      M', '    |  R$ 15,00     |', ' R$ 17,00 |', '-----' * 4)
print('-----' * 4, '|      G', '    |  R$ 19,00     |', ' R$ 21,00 |', '-----' * 4)
print('------' * 14)

# Solicitar ao usuário que escolha o sabor e o tamanho
sabor = input('Escolha o sabor (CP/AC): ').lower()
sabor_escolhido = escolha_sabor(sabor)

tamanho = input('Escolha o tamanho (P/M/G): ').lower()
tamanho_escolhido = escolha_tamanho(tamanho)

# Adicionar mais pedidos
adicionando_pedido(sabor_escolhido, tamanho_escolhido, pedidos)

# Calcular o total dos pedidos
total = sum(pedidos)

# Exibir os dados escolhidos e o total do pedido
print('Sabor escolhido:', sabor_escolhido.upper())
print('Tamanho escolhido:', tamanho_escolhido.upper())
print('O total do pedido foi R$ {:.2f}'.format(total))

def escolha_servico(servico_selecionado):
    while True:
        if servico_selecionado.lower() in ['dig', 'ico', 'ipb', 'fot']:
            return servico_selecionado.lower()
        else:
            print('Escolha inválida')
            servico_selecionado = input('Entre com o tipo de serviço desejado: ').lower()

def valor_paginas(servico_selecionado, selecao_paginas):
    if servico_selecionado == 'dig':
        return selecao_paginas * 1.10
    elif servico_selecionado == 'ico':
        return selecao_paginas * 1.00
    elif servico_selecionado == 'ipb':
        return selecao_paginas * 0.40
    elif servico_selecionado == 'fot':
        return selecao_paginas * 0.20

def quantidade_paginas(selecao_paginas):
    while True:
        if selecao_paginas >= 20000:
            print('Não aceitamos tantas páginas de uma vez, por favor, entre com a quantidade de páginas novamente')
            selecao_paginas = int(input('Quantas páginas deseja: '))
        else:
            return selecao_paginas  # Retorna a quantidade de páginas válida

def num_pagina(selecao_paginas):
    while True:
        if selecao_paginas < 20:
            return selecao_paginas
        elif 20 <= selecao_paginas < 200:
            return selecao_paginas * (15 / 100)  # Desconto de 15%
        elif 200 <= selecao_paginas < 2000:
            return selecao_paginas * (20 / 100)  # Desconto de 20%
        elif 2000 <= selecao_paginas < 20000:
            return selecao_paginas * (25 / 100)  # Desconto de 25%

def extra(servico_extra):
    while True:
        if servico_extra == '1':
            return 15.00
        elif servico_extra == '2':
            return 25.00
        elif servico_extra == '0':
            return 0.00
        else:
            print('Escolha um serviço extra válido')
            servico_extra = input('Deseja adicionar mais algum serviço?: ')

def main():
    print('Bem-vindo a impressões e encadernamento do Ruan Dias de Souza')
    print('DIG - Digitalização')
    print('ICO - Impressão Colorida')
    print('IPB - Impressão Preto e Branco')
    print('FOT - Fotocópia')
    servico_selecionado = input('Entre com o tipo de serviço desejado: ').lower()

    # Verifica se o serviço selecionado é válido
    servico = escolha_servico(servico_selecionado)

    selecao_paginas = int(input('Quantas páginas deseja: '))
    selecao_paginas = quantidade_paginas(selecao_paginas)  # Verifica se a quantidade de páginas é válida

    # Calcula o valor das páginas
    valor_paginas_total = valor_paginas(servico, selecao_paginas)

    print('1 - Encadernação Simples - R$10,00')
    print('2 - Encadernação Capa Dura - R$25,00')
    print('0 - Não desejo mais nada')
    servico_extra = input('Deseja adicionar mais algum serviço?: ')

    # Calcula o valor dos serviços extras
    valor_extra = extra(servico_extra)

    # Calcula o valor total
    valor_final = valor_paginas_total + valor_extra

    print('Total: R$ {:.2f}. Serviço: {} * páginas: {} + extra(s): {}'.format(valor_final, servico, selecao_paginas, valor_extra))

main()

# Variáveis globais
lista_livro = []
id_global = 0

# Função para cadastrar um livro
def cadastrar_livro(id):
    global id_global
    nome_livro = input('Qual o nome do livro?: ')
    nome_autor = input('Qual o nome do autor?: ')
    editora_do_livro = input('Qual o nome da editora do livro?: ')
    lista_livro.append({'id': id, 'titulo': nome_livro, 'autor': nome_autor, 'editora': editora_do_livro})
    id_global += 1

# Função para consultar livros
def consultar_livro():
    while True:
        print('\nMenu de Consulta:')
        print('1. Consultar Todos')
        print('2. Consultar por Id')
        print('3. Consultar por Autor')
        print('4. Retornar ao menu principal')

        opcao_consulta = input('Digite o número da opção desejada: ')
        if opcao_consulta == '1':
            print('\nTodos os livros cadastrados:')
            for livro in lista_livro:
                print(livro)
        elif opcao_consulta == '2':
            id_procurado = int(input('Digite o ID do livro que deseja consultar: '))
            livro_encontrado = consultar_por_id(id_procurado)
            if livro_encontrado:
                print('\nLivro encontrado:')
                print(livro_encontrado)
            else:
                print('\nLivro não encontrado.')
        elif opcao_consulta == '3':
            autor_procurado = input('Digite o nome do autor que deseja consultar: ')
            livros_autor = consultar_por_autor(autor_procurado)
            if livros_autor:
                print('\nLivros encontrados do autor:')
                for livro in livros_autor:
                    print(livro)
            else:
                print('\nAutor não encontrado.')
        elif opcao_consulta == '4':
            break
        else:
            print('Opção inválida. Por favor, escolha uma opção válida.')

# Função para remover um livro
def remover_livro():
    id_remover = int(input('Digite o ID do livro que deseja remover: '))
    for livro in lista_livro:
        if livro['id'] == id_remover:
            lista_livro.remove(livro)
            print('Livro removido com sucesso.')
            break
    else:
        print('Livro não encontrado.')

# Função para consultar um livro pelo ID
def consultar_por_id(id_livro):
    for livro in lista_livro:
        if livro['id'] == id_livro:
            return livro
    return None

# Função para consultar livros por autor
def consultar_por_autor(autor):
    livros_autor = []
    for livro in lista_livro:
        if livro['autor'].lower() == autor.lower():
            livros_autor.append(livro)
    return livros_autor

# Função principal
def main():
    print('Bem-vindo à Biblioteca Digital do Ruan Dias de Souza')
    while True:
        print('\nMenu Principal:')
        print('1. Cadastrar Livro')
        print('2. Consultar Livro')
        print('3. Remover Livro')
        print('4. Encerrar Programa')

        opcao = input('Digite o número da opção desejada: ')
        if opcao == '1':
            cadastrar_livro(id_global)
        elif opcao == '2':
            consultar_livro()
        elif opcao == '3':
            remover_livro()
        elif opcao == '4':
            print('Encerrando o programa...')
            break
        else:
            print('Opção inválida. Por favor, escolha uma opção válida.')

if __name__ == "__main__":
    main()